#!/usr/bin/env node
/**
 * Static site generator for nikosninosg.github.io. Zero dependencies, Node >= 18.
 *
 *   node src/build.mjs                    render everything into the repo root
 *   node src/build.mjs --check            render in memory, exit 1 if committed output differs (CI / pre-commit)
 *   node src/build.mjs --watch            rebuild when content/ or src/ change
 *   node src/build.mjs --serve [port]     build, watch and serve the repo root (default port 4000)
 *   node src/build.mjs --clean-stale      list generated files that are no longer produced (add --delete to remove them)
 *
 * Output is deterministic (no timestamps), so `--check` is a reliable "did you forget to rebuild?" test.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync, rmSync, watch, createReadStream } from 'node:fs';
import { createServer } from 'node:http';
import { spawnSync } from 'node:child_process';
import { dirname, join, relative, extname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { isRaw } from './lib/html.mjs';
import { loadContent, ContentError, ROOT } from './lib/content.mjs';
import { createPageCtx, renderDocument, renderRedirect, absUrl } from './lib/layout.mjs';

import home from './pages/home.mjs';
import about from './pages/about.mjs';
import experience from './pages/experience.mjs';
import projects from './pages/projects.mjs';
import project from './pages/project.mjs';
import contact from './pages/contact.mjs';
import notfound from './pages/notfound.mjs';

const SELF = fileURLToPath(import.meta.url);
export const GENERATED_MARKER = 'Generated by src/build.mjs';

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/** Static page plan. Project pages are appended per content/projects/*.json. */
const STATIC_PAGES = [
  { id: 'home', out: 'index.html', render: home, sitemap: 1.0 },
  { id: 'about', out: 'about.html', render: about, sitemap: 0.8 },
  { id: 'experience', out: 'experience.html', render: experience, sitemap: 0.8 },
  { id: 'projects', out: 'projects.html', render: projects, sitemap: 0.8 },
  { id: 'contact', out: 'contact.html', render: contact, sitemap: 0.7 },
  // 404 is served by GitHub Pages from any depth -> absolute site-root URLs (see notfound.mjs).
  { id: 'notfound', out: '404.html', render: notfound, rootRelative: true, sitemap: null },
];

/** Validate the object a page module returned; throws with the page id so mistakes are easy to find. */
function checkPage(plan, page, warnings) {
  const who = `page "${plan.id}" (${plan.out})`;
  if (!page || typeof page !== 'object') throw new Error(`${who}: render() must return an object`);
  if (page.path !== plan.out) throw new Error(`${who}: returned path "${page.path}" but is planned at "${plan.out}"`);
  if (typeof page.id !== 'string') throw new Error(`${who}: missing string "id"`);
  if (!isRaw(page.body)) throw new Error(`${who}: "body" must be an html\`\` result (or raw()), got ${typeof page.body}`);
  if (page.id !== 'home' && !page.title) throw new Error(`${who}: missing "title"`);
  for (const key of ['css', 'js']) {
    if (!Array.isArray(page[key] ?? [])) throw new Error(`${who}: "${key}" must be an array`);
    for (const f of page[key] ?? []) {
      if (!existsSync(join(ROOT, f))) warnings.push(`${who}: ${key} file "${f}" does not exist yet`);
    }
  }
}

/** Render every output file in memory: Map<repo-relative path, string>. */
export function renderAll() {
  const ctx = loadContent();
  const warnings = [...ctx.warnings];
  const files = new Map();
  const sitemapEntries = [];

  const plans = [
    ...STATIC_PAGES,
    ...ctx.projects.map((p) => ({ id: 'project', out: `projects/${p.slug}.html`, render: project, arg: p, sitemap: 0.6 })),
  ];

  for (const plan of plans) {
    const pctx = createPageCtx(ctx, plan.out, { rootRelative: plan.rootRelative });
    const page = plan.render(pctx, plan.arg);
    checkPage(plan, page, warnings);
    files.set(plan.out, renderDocument(pctx, page));
    if (plan.sitemap !== null) sitemapEntries.push({ loc: absUrl(ctx.site.url.replace(/\/+$/, ''), plan.out), priority: plan.sitemap });
  }

  // Legacy project URLs -> tiny redirect stubs (skipped when a legacy path equals a real page).
  for (const p of ctx.projects) {
    for (const legacy of p.legacyPaths) {
      if (files.has(legacy)) continue;
      files.set(legacy, renderRedirect({ site: ctx.site, fromPath: legacy, toPath: `projects/${p.slug}.html` }));
    }
  }

  files.set('sitemap.xml', renderSitemap(sitemapEntries));
  files.set('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${absUrl(ctx.site.url.replace(/\/+$/, ''), 'sitemap.xml')}\n`);
  files.set('.nojekyll', ''); // keep GitHub Pages from running Jekyll over the repo

  return { files, ctx, warnings };
}

function renderSitemap(entries) {
  const urls = entries
    .map((e) => `  <url>\n    <loc>${e.loc}</loc>\n    <priority>${e.priority.toFixed(1)}</priority>\n  </url>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

// ---------------------------------------------------------------------------
// Disk helpers
// ---------------------------------------------------------------------------
const log = (...a) => console.log(...a);
const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} KB`;
const readOrNull = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : null);

function writeAll(files) {
  let written = 0;
  let unchanged = 0;
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel);
    if (readOrNull(abs) === content) {
      unchanged++;
      continue;
    }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    written++;
    log(`  wrote   ${rel.padEnd(38)} ${kb(content)}`);
  }
  return { written, unchanged };
}

/** Generated files on disk (identified by the marker comment) that the current build no longer produces. */
function findStale(files) {
  const stale = [];
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      if (['node_modules', '.git', '.idea', 'assets', 'content', 'src'].includes(name)) continue;
      const abs = join(dir, name);
      const st = statSync(abs);
      if (st.isDirectory()) walk(abs);
      else if (name.endsWith('.html')) {
        const rel = relative(ROOT, abs).split(sep).join('/');
        if (!files.has(rel) && readFileSync(abs, 'utf8').includes(GENERATED_MARKER)) stale.push(rel);
      }
    }
  };
  walk(ROOT);
  return stale.sort();
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------
function runBuild() {
  const t0 = performance.now();
  const { files, warnings } = renderAll();
  warnings.forEach((w) => log(`  warning ${w}`));
  const { written, unchanged } = writeAll(files);
  const stale = findStale(files);
  stale.forEach((s) => log(`  stale   ${s} (generated earlier, no longer produced; run --clean-stale)`));
  log(`Built ${files.size} files: ${written} written, ${unchanged} unchanged (${Math.round(performance.now() - t0)} ms).`);
}

function runCheck() {
  const { files, warnings } = renderAll();
  warnings.forEach((w) => log(`  warning ${w}`));
  const problems = [];
  for (const [rel, content] of files) {
    const onDisk = readOrNull(join(ROOT, rel));
    if (onDisk === null) problems.push(`missing   ${rel}`);
    else if (onDisk !== content) problems.push(`outdated  ${rel}`);
  }
  findStale(files).forEach((s) => problems.push(`stale     ${s}`));
  if (problems.length) {
    console.error(`Generated output is out of date:\n${problems.map((p) => `  ${p}`).join('\n')}\nRun: node src/build.mjs`);
    process.exit(1);
  }
  log(`OK: ${files.size} generated files match the sources.`);
}

function runCleanStale(del) {
  const { files } = renderAll();
  const stale = findStale(files);
  if (!stale.length) return log('No stale generated files.');
  for (const s of stale) {
    if (del) {
      rmSync(join(ROOT, s));
      log(`  deleted ${s}`);
    } else log(`  stale   ${s}`);
  }
  if (!del) log('Re-run with --delete to remove them.');
}

/** Rebuild in a fresh process on every change so edited ES modules are never served from the import cache. */
function runWatch() {
  const rebuild = () => {
    const res = spawnSync(process.execPath, [SELF], { stdio: 'inherit' });
    if (res.status !== 0) log('Build failed; waiting for the next change…');
  };
  rebuild();
  let timer = null;
  for (const dir of ['content', 'src']) {
    try {
      watch(join(ROOT, dir), { recursive: true }, (_event, filename) => {
        if (!filename || /(^|[\\/])\.|~$|\.swp$/.test(String(filename))) return;
        clearTimeout(timer);
        timer = setTimeout(() => {
          log(`\nChange in ${dir}/${filename}, rebuilding…`);
          rebuild();
        }, 120);
      });
    } catch (err) {
      console.error(`Cannot watch ${dir}/ (${err.message}). Recursive watching needs Node >= 20 on Linux.`);
      process.exit(1);
    }
  }
  log('Watching content/ and src/ for changes (Ctrl+C to stop).');
}

const MIME = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8', '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.webp': 'image/webp', '.avif': 'image/avif', '.ico': 'image/x-icon', '.woff': 'font/woff',
  '.woff2': 'font/woff2', '.ttf': 'font/ttf', '.pdf': 'application/pdf', '.mp4': 'video/mp4', '.webm': 'video/webm',
  '.webmanifest': 'application/manifest+json', '.map': 'application/json',
};

/** Tiny static server mimicking GitHub Pages (/about -> about.html, unknown -> 404.html with status 404). */
function runServe(port) {
  const resolveFile = (urlPath) => {
    const abs = resolve(ROOT, `.${decodeURIComponent(urlPath)}`);
    if (abs !== ROOT && !abs.startsWith(ROOT + sep)) return null; // path traversal
    const candidates = [abs, `${abs}.html`, join(abs, 'index.html')];
    return candidates.find((c) => existsSync(c) && statSync(c).isFile()) ?? null;
  };
  const server = createServer((req, res) => {
    let file = null;
    try {
      file = resolveFile(new URL(req.url, 'http://localhost').pathname);
    } catch {
      /* malformed URL -> 404 */
    }
    let status = 200;
    if (!file) {
      status = 404;
      file = join(ROOT, '404.html');
    }
    if (!existsSync(file)) {
      res.writeHead(404, { 'content-type': 'text/plain' }).end('Not found');
      return;
    }
    res.writeHead(status, { 'content-type': MIME[extname(file).toLowerCase()] ?? 'application/octet-stream', 'cache-control': 'no-cache' });
    if (req.method === 'HEAD') return void res.end();
    createReadStream(file).pipe(res);
  });
  server.listen(port, '127.0.0.1', () => log(`Serving ${ROOT}\n  http://127.0.0.1:${port}/`));
  server.on('error', (err) => {
    console.error(`Server error: ${err.message}`);
    process.exit(1);
  });
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------
function main(argv) {
  const has = (f) => argv.includes(f);
  const serveIdx = argv.indexOf('--serve');
  try {
    if (has('--check')) return runCheck();
    if (has('--clean-stale')) return runCleanStale(has('--delete'));
    if (serveIdx >= 0) {
      const next = argv[serveIdx + 1];
      const port = /^\d+$/.test(next ?? '') ? Number(next) : 4000;
      runWatch();
      return runServe(port);
    }
    if (has('--watch')) return runWatch();
    return runBuild();
  } catch (err) {
    if (err instanceof ContentError) console.error(`\n${err.message}\n`);
    else console.error(err);
    process.exit(1);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === SELF) main(process.argv.slice(2));
